# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types: [ "opened" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "${{ github.event.issue.body != '' }}"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |          
          #!/bin/bash          
          data=$(head -n 1 $GITHUB_WORKSPACE/EarthshakerNinjasData/EarthshakerNinjasData.lua)
          if [[ ${data} == "ESN_DATA_SHITLIST = {};" ]];
          then
              out="${data:0:${#data}-2}\"${{ github.event.issue.body }}\"};"
          else
              out="${data:0:${#data}-2},\"${{ github.event.issue.body }}\"};"
          fi
          echo $out > "$GITHUB_WORKSPACE/EarthshakerNinjasData/EarthshakerNinjasData.lua"
                    
      - uses: peter-evans/close-issue@v2
        with:
          comment: |
            Issue has been handled successfully and the code has been updated by GitHub Action
            Auto-closing this issue. 
            
      - name: Modify version number
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: 'Version: ([0-9\.]*)'
          replacement: 'Version: 0.0.${{ github.run_number }}'
          flags: "g"                  # Optional, defaults to "g"
          include: '*\.toc'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: '.'                   # Optional, defaults to '.' 
               
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated release version and list"
          tagging_message: alpha-${{ github.run_number }}
